FROM couchdb:3.0.1
HEALTHCHECK --interval=10s --timeout=15s   --retries=200 \
  CMD true
ARG NODENAME=omni
ARG COUCHDB_PASSWORD=123456
ARG COUCHDB_USER=admin
ADD couchdb.ini /opt/couchdb/etc/local.d/couchdb.ini
ADD casts.json casts.json
RUN bash -c "/docker-entrypoint.sh /opt/couchdb/bin/couchdb &" && sleep 5 && curl -X PUT http://$COUCHDB_USER:$COUCHDB_PASSWORD@127.0.0.1:5984/_users \
  && curl -X PUT http://$COUCHDB_USER:$COUCHDB_PASSWORD@127.0.0.1:5984/_replicator && curl -X PUT http://$COUCHDB_USER:$COUCHDB_PASSWORD@127.0.0.1:5984/_global_changes \
  && curl -X PUT http://$COUCHDB_USER:$COUCHDB_PASSWORD@127.0.0.1:5984/casts \
  && curl -X PUT --data "@casts.json" http://$COUCHDB_USER:$COUCHDB_PASSWORD@127.0.0.1:5984/casts/_design/casts